src/Nte/Aplicacao/FrigaBundle/Entity/FrigaEditalCargo.php
<?php

/*
 * This file is part of  Friga - https://nte.ufsm.br/friga.
 * (c) Friga
 * Friga is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Friga is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Friga.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace Nte\Aplicacao\FrigaBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * FrigaEditalCargo.
 *
 * @ORM\Table(name="friga_edital_cargo")
 *
 * @ORM\Entity
 */
class FrigaEditalCargo
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     *
     * @ORM\Id
     *
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="descricao", type="text", length=65535, nullable=true)
     */
    private $descricao;

    /**
     * @var string
     *
     * @ORM\Column(name="ativo", type="integer", nullable=true)
     */
    private $ativo;

    /**
     * @var string
     *
     * @ORM\Column(name="ponto_corte", type="integer", nullable=true)
     */
    private $pontoCorte;

    /**
     * @var FrigaEdital
     *
     * @ORM\ManyToOne(targetEntity="FrigaEdital", inversedBy="cargo")
     *
     * @ORM\JoinColumns({
     *
     *   @ORM\JoinColumn(name="id_edital", referencedColumnName="id")
     * })
     */
    private $idEdital;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Nte\Aplicacao\FrigaBundle\Entity\FrigaEditalUsuario", mappedBy="idEditalCargo")
     */
    protected $idEditalUsuario;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="Nte\Aplicacao\FrigaBundle\Entity\FrigaEditalUsuarioConvite", mappedBy="idEditalCargo")
     */
    protected $idEditalUsuarioConvite;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Nte\Aplicacao\FrigaBundle\Entity\FrigaInscricao", mappedBy="idCargo")
     */
    protected $idEditalUsuarioInscrito;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->idEditalUsuario = new ArrayCollection();
        $this->idEditalUsuarioConvite = new ArrayCollection();
        $this->idEditalUsuarioInscrito = new ArrayCollection();
    }

    public function __clone()
    {
        $this->idEditalUsuario = new ArrayCollection();
        $this->idEditalUsuarioConvite = new ArrayCollection();
        $this->idEditalUsuarioInscrito = new ArrayCollection();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getPontoCorte()
    {
        return $this->pontoCorte;
    }

    /**
     * @param string $pontoCorte
     *
     * @return FrigaEditalCargo
     */
    public function setPontoCorte($pontoCorte)
    {
        $this->pontoCorte = $pontoCorte;

        return $this;
    }

    /**
     * Set descricao.
     *
     * @param string $descricao
     *
     * @return FrigaEditalCargo
     */
    public function setDescricao($descricao)
    {
        $this->descricao = $descricao;

        return $this;
    }

    /**
     * Get descricao.
     *
     * @return string
     */
    public function getDescricao()
    {
        return $this->descricao;
    }

    /**
     * Set idEdital.
     *
     * @return FrigaEditalCargo
     */
    public function setIdEdital(FrigaEdital $idEdital = null)
    {
        $this->idEdital = $idEdital;

        return $this;
    }

    /**
     * Get idEdital.
     *
     * @return FrigaEdital
     */
    public function getIdEdital()
    {
        return $this->idEdital;
    }

    /**
     * @return string
     */
    public function getAtivo()
    {
        return $this->ativo;
    }

    /**
     * @param string $ativo
     *
     * @return FrigaEditalCargo
     */
    public function setAtivo($ativo)
    {
        $this->ativo = $ativo;

        return $this;
    }

    /**
     * Add idEditalUsuario.
     *
     * @return FrigaEditalCargo
     */
    public function addIdEditalUsuario(FrigaEditalUsuario $idEditalUsuario)
    {
        if (!$this->idEditalUsuario->contains($idEditalUsuario)) {
            $this->idEditalUsuario->add($idEditalUsuario->addIdEditalCargo($this));
        }

        return $this;
    }

    /**
     * Remove idEditalUsuario.
     */
    public function removeIdEditalUsuario(FrigaEditalUsuario $idEditalUsuario)
    {
        $this->idEditalUsuario->removeElement($idEditalUsuario);
    }

    /**
     * Get idEditalUsuario.
     *
     * @return ArrayCollection
     */
    public function getIdEditalUsuario()
    {
        return $this->idEditalUsuario;
    }

    /**
     * Add idEditalUsuario.
     *
     * @return FrigaEditalCargo
     */
    public function addIdEditalUsuarioConvite(FrigaEditalUsuarioConvite $idEditalUsuarioConvite)
    {
        if (!$this->idEditalUsuarioConvite->contains($idEditalUsuarioConvite)) {
            $this->idEditalUsuarioConvite->add($idEditalUsuarioConvite->addIdEditalCargo($this));
        }

        return $this;
    }

    /**
     * Remove idEditalUsuario.
     */
    public function removeIdEditalUsuarioConvite(FrigaEditalUsuarioConvite $idEditalUsuarioConvite)
    {
        $this->idEditalUsuarioConvite->removeElement($idEditalUsuarioConvite);
    }

    /**
     * Get idEditalUsuario.
     *
     * @return ArrayCollection
     */
    public function getIdEditalUsuarioConvite()
    {
        return $this->idEditalUsuarioConvite;
    }

    /**
     * @return ArrayCollection
     */
    public function getIdEditalUsuarioInscrito()
    {
        return $this->idEditalUsuarioInscrito;
    }

    /**
     * @return ArrayCollection
     */
    public function getInscricaoValida()
    {
        return $this->getIdEditalUsuarioInscrito()->filter(
            function(FrigaInscricao $inscricao) {
                return -999 !== $inscricao->getIdSituacao();
            });
    }

    /**
     * @return ArrayCollection
     */
    public function getInscricaoSituacao($situacao = 0)
    {
        return $this->getIdEditalUsuarioInscrito()->filter(
            function(FrigaInscricao $inscricao) use ($situacao) {
                return $inscricao->getIdSituacao() === $situacao;
            });
    }
}

src/Nte/Aplicacao/FrigaBundle/Resources/views/edital/form-avaliador-cargo.html.twig
{% extends 'base.admin.html.twig' %}
{% block titulo %} {{ frigaedital.uuid }}/Avaliadores/Cargo{% endblock %}
{% block breadcumbsTitulo %} {{ frigaedital.uuid }}/Avaliadores/Cargo {% endblock %}
{% block conteudo %}
    {{ form_start(config_form) }}
    <div class="row">
        {{ include('@NteAplicacaoFriga/edital/menu.html.twig', {entidade: frigaedital}) }}
        <div class="col-md-9 col-lg-10">
            <section class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="col-md-4 col-sm-4 control-label">
                                {{ form_label(config_form.idEditalCargo) }}
                            </label>
                            <div class="col-md-8">
                                {{ form_widget(config_form.idEditalCargo) }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-12"><br>
                        <button class="btn btn-primary pull-right" type="submit">
                            <i class="fa fa-save"></i> Salvar
                        </button>
                    </div>
                </div>
            </section>
        </div>
    </div>
    {{ form_end(config_form) }}
{% endblock %}

src/Nte/Aplicacao/FrigaBundle/Resources/views/edital/form-cargo.html.twig
{% extends 'base.admin.html.twig' %}
{% block titulo %} {{ frigaedital.uuid }}/Vaga/Edição{% endblock %}
{% block breadcumbsTitulo %} {{ frigaedital.uuid }}/Vaga/Edição {% endblock %}
{% block conteudo %}
<div class="row">
    {{ include('@NteAplicacaoFriga/edital/menu.html.twig', {entidade: frigaedital}) }}
    <div class="col-md-9 col-lg-10">
        <section class="panel-body">
            {{ form_start(form) }}
            <div class="form-group">
                <label class="col-md-4 col-sm-4 control-label">
                    {{ form_label(form.descricao) }}
                </label>
                <div class="col-md-8">
                    {{ form_widget(form.descricao) }}
                </div>
            </div>
            {{ form_rest(form) }}
            <div class="form-group">
                <button type="submit" class="btn btn-primary center-block"><i class="fa fa-save"></i> Salvar </button>
            </div>
            {{ form_end(form) }}
    </section>
    </div>
</div>
{% endblock %}

src/Nte/Aplicacao/FrigaBundle/Resources/views/edital/form-categoria.html.twig
{% extends 'base.admin.html.twig' %}
{% block titulo %} Edição de Categoria{% endblock %}
{% block breadcumbsTitulo %}Edição de Categoria{% endblock %}
{% block conteudo %}
    <div class="row">
        <div class="col-md-12">
            {% if categoria.id %}
                <div class="panel-body text-right">
                    <a class="btn btn-danger " href="{{ path('edital_categoria_remover', {'id': categoria.id}) }}">
                        Remover
                    </a>
                </div>
                <br>
            {% endif %}
            <div class="panel-body">
                {{ form_start(form) }}
                {{ form_rest(form) }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary center-block"><i class="fa fa-save"></i> Salvar
                    </button>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts2 %}
    <script>
        $('select').select2({
            placeholder: "Selecione um categoria",
            allowClear: true,
        });
    </script>
{% endblock %}

src/Nte/Aplicacao/FrigaBundle/Resources/views/edital/form-etapa-categoria.html.twig
{% extends 'base.admin.html.twig' %}
{% block titulo %} {{ frigaedital.uuid }}/Etapa/Edição {% endblock %}
{% block breadcumbsTitulo %} {{ frigaedital.uuid }}/Etapa/Edição {% endblock %}
{% block conteudo %}
    <div class="row">
        {{ include('@NteAplicacaoFriga/edital/menu.html.twig', {entidade: frigaedital}) }}
        <div class="col-md-9 col-lg-10">
            <section class="panel-body">
                {{ form_start(form) }}
                <div class="form-group">
                    <label class="col-md-4 col-sm-4 control-label">
                        {{ form_label(form.descricao) }}
                    </label>
                    <div class="col-md-8">
                        {{ form_widget(form.descricao) }}
                    </div>
                </div>
                {{ form_rest(form) }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary center-block"><i class="fa fa-save"></i> Salvar </button>
                </div>
                {{ form_end(form) }}
            </section>
        </div>
    </div>
{% endblock %}

src/Nte/Aplicacao/FrigaBundle/Resources/views/edital/form-exportador.html.twig
{% extends 'base.admin.html.twig' %}
{% block titulo %} {{ frigaedital.uuid }}/Exportador{% endblock %}
{% block breadcumbsTitulo %} {{ frigaedital.uuid }}/Exportador {% endblock %}
{% block conteudo %}
    {{ form_start(config_form) }}
    <div class="row">
        {{ include('@NteAplicacaoFriga/edital/menu.html.twig', {entidade: frigaedital}) }}
        <div class="col-md-9 col-lg-10">
            <section class="panel-body">
                <div class="col-md-2">
                    Categorias de Exportação
                </div>
                <div class="col-md-10">
                    {{ form_rest(config_form) }}
                </div>
                <div class="col-md-12 text-center">
                    <br>
                    <button class="btn btn-default" type="submit">
                        <i class="fa fa-download"></i> Exportar Arquivo
                </div>
            </section>
        </div>
    </div>
    {{ form_end(config_form) }}
{% endblock %}

src/Nte/Aplicacao/FrigaBundle/Resources/views/edital/form-pontuacao.html.twig
{% extends 'base.admin.html.twig' %}

{% block titulo %} {{ frigaedital.uuid }}/Pontuação/Edição{% endblock %}
{% block breadcumbsTitulo %} {{ frigaedital.uuid }}/Pontuação/Edição {% endblock %}
{% block conteudo %}
    <div class="row">
        {{ include('@NteAplicacaoFriga/edital/menu.html.twig', {entidade: frigaedital}) }}
        <div class="col-md-9 col-lg-10">
            <section class="panel-body">
                {{ form_start(form) }}
                {{ form_rest(form) }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary center-block"><i class="fa fa-save"></i> Salvar </button>
                </div>
                {{ form_end(form) }}
            </section>
        </div>
    </div>
{% endblock %}

src/Nte/Aplicacao/FrigaBundle/Resources/views/edital/form-resultado.html.twig
{% extends 'base.admin.html.twig' %}
{% block titulo %} {{ frigaedital.uuid }}/Resultado{% endblock %}
{% block breadcumbsTitulo %} {{ frigaedital.uuid }}/Resultado {% endblock %}
{% block conteudo %}
    {{ form_start(config_form) }}
    <div class="row">
        {{ include('@NteAplicacaoFriga/edital/menu.html.twig', {entidade: frigaedital}) }}
        <div class="col-md-9 col-lg-10">
            <section class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="form-group">
                                <label class="col-md-4 col-sm-4 control-label">
                                    Resultados
                                </label>
                                <div class="col-md-8">
                                    {{ form_widget(config_form) }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                    </div>
                </div>
                <div class="col-md-12 text-center">
                    <button class="btn btn-primary " type="submit">
                        <i class="fa fa-save"></i> Salvar
                    </button>
                </div>
            </section>
        </div>
    </div>
    {{ form_end(config_form) }}
{% endblock %}

src/Nte/Aplicacao/FrigaBundle/Resources/views/edital/index-categoria.html.twig
{% extends 'base.admin.html.twig' %}
{% block titulo %} Edital/Categorias{% endblock %}
{% block breadcumbsTitulo %} Categorias {% endblock %}
{% block conteudo %}
    <div class="row">
        <div class="col-md-12">
            <section class="panel-body">
                {% if categoria|length %}
                    <table class="table table-hover table-condesed ">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Categoria</th>
                            <th>
                                <a href="{{ path('edital_categoria_criar') }}"
                                   class="btn btn-primary pull-right">
                                    <i class="fa fa-plus-circle"></i> Adicionar
                                </a>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for c in categoria %}
                            <tr>
                                <td>{{ c.id }}</td>
                                <td>{{ c.descricao }}</td>
                                <td>
                                    <div class="btn-group btn-group-sm pull-right">
                                        <a class="btn btn-default"
                                           href="{{ path('edital_categoria_editar',{id: c.id}) }}">
                                            <i class="fa fa-edit"></i> Editar
                                        </a>
                                        <a class="btn btn-default"
                                           href="{{ path('edital_categoria_remover',{id: c.id}) }}">
                                            <i class="fa fa-edit"></i> Remover
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <section class="body-error error-inside">
                        <div class="center-error">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="main-error mb-xlg">
                                        <h2 class="error-code text-dark text-center text-weight-semibold m-none">
                                            <i class="icon icon-settings text-primary"></i>
                                        </h2>
                                        <p class="error-explanation text-center text-primary">
                                            <br><b>Nenhuma categoria foi criada </b> até o momento.<br>
                                            <br>
                                            <br>
                                            <a href="{{ path('edital_categoria_criar') }}" class="btn btn-primary">
                                                <i class="fa fa-plus-circle"></i> Criar Categoria
                                            </a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                {% endif %}
            </section>
        </div>
    </div>
{% endblock %}

src/Nte/Aplicacao/FrigaBundle/Resources/views/edital/index.html.twig
{% extends 'base.admin.html.twig' %}
{% block titulo %} Editais {% endblock %}
{% block breadcumbsTitulo %}Editais {% endblock %}
{% block conteudo %}
    <div class="row">
        <div class="btn-group">
            {% set classe1 = 'edital_index_rascunho' == app.request.attributes.get('_route')?"active":"" %}
            <a class="btn btn-default {{ classe1 }}" href="{{ path('edital_index_rascunho') }}">
                <i class="icon icon-pencil"></i> Rascunho
            </a>
            {% set classe1 = 'edital_index' == app.request.attributes.get('_route')?"active":"" %}
            <a class="btn btn-default {{ classe1 }}" href="{{ path('edital_index') }}">
                <i class="icon icon-star"></i> Aberto
            </a>
            {% set classe1 = 'edital_index_encerrado' == app.request.attributes.get('_route')?"active":"" %}
            <a class="btn btn-default {{ classe1 }}" href="{{ path('edital_index_encerrado') }}">
                <i class="icon icon-close"></i> Encerrados
            </a>
        </div>
        <!--<a href="{{ path('edital_criar') }}" class="btn btn-primary pull-right">
            <i class="fa fa-plus"></i> Criar Edital
        </a>-->
    </div>
    {% for edital in editais %}
        <div class="row">
            <section class="panel panel-horizontal">
                <header class="panel-heading bg-white">
                    <div class="panel-heading-icon bg-primary mt-sm">
                        <i class="fa fa-exchange"></i>
                    </div>
                </header>
                <div class="panel-body p-lg">
                    <h4 class="text-weight-semibold mt-sm">
                        <a href="{{ path('edital_editar', { 'uuid': edital.uuid }) }}">
                            {{ edital.titulo }}
                        </a>
                        <i class="fa fa-{% if edital.publico >0 %}eye{% else %}eye-slash{% endif %} pull-right"></i>
                    </h4>
                    <div class="row">
                        <div class="col-sm-12 col-md-6 text-justify">
                            <p>{{ edital.sobre }}</p>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <div class="row">
                                <div class="col-sm-6 col-md-6 ">
                                    <section class="panel panel-featured-bottom panel-featured-primary">
                                        <div class="panel-body">
                                            <div class="widget-summary widget-summary-sm ">
                                                <div class="widget-summary-col widget-summary-col-icon">
                                                    <div class="summary-icon  bg-primary">
                                                        <i class="fa fa-user-secret"></i>
                                                    </div>
                                                </div>
                                                <div class="widget-summary-col">
                                                    <div class="summary">
                                                        <a href="{{ path('relatorio_inscritos', {'uuid': edital.uuid}) }}"
                                                           class="text-muted text-uppercase">
                                                            <h4 class="title">INSCRITOS</h4>
                                                        </a>
                                                        <div class="info">
                                                            <strong class="amount">{{ edital.inscricaoValida|length }}</strong>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </section>
                                </div>
                                <div class="col-sm-6 col-md-6 ">
                                    <section class="panel panel-featured-bottom panel-featured-tertiary">
                                        <div class="panel-body">
                                            <div class="widget-summary widget-summary-sm ">
                                                <div class="widget-summary-col widget-summary-col-icon">
                                                    <div class="summary-icon  bg-tertiary">
                                                        <i class="fa fa-money"></i>
                                                    </div>
                                                </div>
                                                <div class="widget-summary-col">
                                                    <div class="summary">
                                                        <a href="{{ path('edital_cargo', {'uuid': edital.uuid}) }}"
                                                           class="text-muted text-uppercase">
                                                            <h4 class="title">VAGAS</h4>
                                                        </a>
                                                        <div class="info">
                                                            <strong class="amount">{{ edital.cargo|length }} </strong>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </section>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6 col-md-6 ">
                                    <section class="panel panel-featured-bottom panel-featured-secondary">
                                        <div class="panel-body">
                                            <div class="widget-summary widget-summary-sm ">
                                                <div class="widget-summary-col widget-summary-col-icon">
                                                    <div class="summary-icon  bg-secondary">
                                                        <i class="fa fa-user-md"></i>
                                                    </div>
                                                </div>
                                                <div class="widget-summary-col">
                                                    <div class="summary">
                                                        <a href="{{ path('edital_etapa', {'uuid': edital.uuid}) }}"
                                                           class="text-muted text-uppercase">
                                                            <h4 class="title">ETAPAS</h4>
                                                        </a>
                                                        <div class="info">
                                                            <strong class="amount">{{ edital.etapa|length }}</strong>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </section>
                                </div>
                                <div class="col-sm-6 col-md-6 ">
                                    <section class="panel panel-featured-bottom panel-featured-quartenary">
                                        <div class="panel-body">
                                            <div class="widget-summary widget-summary-sm ">
                                                <div class="widget-summary-col widget-summary-col-icon">
                                                    <div class="summary-icon  bg-quartenary">
                                                        <i class="fa fa-asterisk"></i>
                                                    </div>
                                                </div>
                                                <div class="widget-summary-col">
                                                    <div class="summary">
                                                        <a href="{{ path('edital_avaliador', {'uuid': edital.uuid}) }}"
                                                           class="text-muted text-uppercase">
                                                            <h4 class="title">AVALIADORES</h4>
                                                        </a>
                                                        <div class="info">
                                                            <strong class="amount">{{ edital.idEditalUsuario|length }} </strong>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </section>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 text-left">
                            <i class="fa fa-clock-o"></i>
                            <strong>Publicação Oficial:</strong> {{ edital.dataPublicacaoOficial|date('d/m/Y') }} &nbsp;&nbsp;
                            <i class="fa fa-calendar"></i> <strong>Inscrições:</strong>
                            {% if edital.periodoInscricao %}
                                De {{ edital.periodoInscricao.dataInicial|date('d/m/Y') }}
                                A {{ edital.periodoInscricao.dataFinal|date('d/m/Y') }}
                            {% else %}
                                <a href="{{ path('edital_etapa_criar', {tipo: 1 ,'uuid': edital.uuid}) }}">Definir
                                    período</a>
                            {% endif %}
                            &nbsp;&nbsp;
                            <i class="fa fa-trophy"></i> <strong>Resultado Final:</strong>
                            {% if edital.resultadoFinal %}
                                {{ edital.resultadoFinal.dataDivulgacao|date('d/m/Y') }}
                            {% else %}
                                <a href="{{ path('edital_etapa_criar', {tipo: 4, 'uuid': edital.uuid}) }}">Definir
                                    período</a>
                            {% endif %}
                        </div>
                        <div class="col-md-6 text-right">
                            <a href="{{ path('edital_clone', {'uuid': edital.uuid}) }}"><i class="fa fa-copy"></i>
                                Clonar Edital</a>
                            &nbsp;&nbsp;
                            <!--<a href="{{ path('edital_remover', {'uuid': edital.uuid}) }}"><i class="fa fa-remove"></i> Remover Edital</a>-->
                            <a href="#"><i class="fa fa-remove"></i> Remover Edital</a>
                            &nbsp;&nbsp;
                        </div>

                    </div>
                </div>
            </section>
        </div>
    {% endfor %}
{% endblock %}