src/Nte/Aplicacao/FrigaBundle/Entity/FrigaClassificacao.php
<?php

/*
 * This file is part of  Friga - https://nte.ufsm.br/friga.
 * (c) Friga
 * Friga is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Friga is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Friga.  If not, see <https://www.gnu.org/licenses/>.
 */

namespace Nte\Aplicacao\FrigaBundle\Entity;

use Doctrine\ORM\Event\PreUpdateEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Nte\UsuarioBundle\Entity\Usuario;

/**
 * FrigaClassificacao.
 *
 * @ORM\Table(name="friga_classificacao")
 *
 * @ORM\Entity
 *
 * @ORM\HasLifecycleCallbacks()
 */
class FrigaClassificacao
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     *
     * @ORM\Id
     *
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var float
     *
     * @ORM\Column(name="valor", type="decimal", precision=10, scale=5, nullable=true)
     */
    private $valor;

    /**
     * @var int
     *
     * @ORM\Column(name="posicao", type="integer", nullable=true)
     */
    private $posicao;

    /**
     * @var int
     *
     * @ORM\Column(name="posicao_anterior", type="integer", nullable=true)
     */
    private $posicaoAnterior;

    /**
     * @var bool
     *
     * @ORM\Column(name="empate", type="boolean", nullable=true)
     */
    private $empate;

    /**
     * @var string
     *
     * @ORM\Column(name="uuid", type="string", length=255, nullable=true)
     */
    private $uuid;

    /**
     * @var string
     *
     * @ORM\Column(name="observacao", type="text", nullable=true)
     */
    private $observacao;

    /**
     * @var int
     *
     * @ORM\Column(name="id_situacao", type="integer", nullable=true)
     */
    private $idSituacao;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="registro_data_criacao", type="datetime", nullable=true)
     */
    private $registroDataCriacao;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="registro_data_atualizacao", type="datetime", nullable=true)
     */
    private $registroDataAtualizacao;

    /**
     * @var FrigaEdital
     *
     * @ORM\ManyToOne(targetEntity="FrigaEdital")
     *
     * @ORM\JoinColumns({
     *
     *   @ORM\JoinColumn(name="id_edital", referencedColumnName="id")
     * })
     */
    private $idEdital;

    /**
     * @var FrigaEditalEtapa
     *
     * @ORM\ManyToOne(targetEntity="Nte\Aplicacao\FrigaBundle\Entity\FrigaEditalEtapa", inversedBy="classificacao")
     *
     * @ORM\JoinColumns({
     *
     *   @ORM\JoinColumn(name="id_etapa", referencedColumnName="id")
     * })
     */
    private $idEtapa;

    /**
     * @var FrigaEditalCargo
     *
     * @ORM\ManyToOne(targetEntity="FrigaEditalCargo")
     *
     * @ORM\JoinColumns({
     *
     *   @ORM\JoinColumn(name="id_cargo", referencedColumnName="id")
     * })
     */
    private $idCargo;

    /**
     * @var FrigaEditalCota
     *
     * @ORM\ManyToOne(targetEntity="Nte\Aplicacao\FrigaBundle\Entity\FrigaEditalCota")
     *
     * @ORM\JoinColumns({
     *
     *   @ORM\JoinColumn(name="id_cota", referencedColumnName="id")
     * })
     */
    private $idCota;

    /**
     * @var FrigaInscricao
     *
     * @ORM\ManyToOne(targetEntity="FrigaInscricao", inversedBy="classificacao")
     *
     * @ORM\JoinColumns({
     *
     *   @ORM\JoinColumn(name="id_inscricao", referencedColumnName="id")
     * })
     */
    private $idInscricao;

    /**
     * @var Usuario
     *
     * @ORM\ManyToOne(targetEntity="Nte\UsuarioBundle\Entity\Usuario")
     *
     * @ORM\JoinColumns({
     *
     *   @ORM\JoinColumn(name="id_usuario", referencedColumnName="id")
     * })
     */
    private $idUsuario;

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set valor.
     *
     * @param string $valor
     *
     * @return FrigaClassificacao
     */
    public function setValor($valor)
    {
        $this->valor = $valor;

        return $this;
    }

    /**
     * Get valor.
     *
     * @return string
     */
    public function getValor()
    {
        return $this->valor;
    }

    /**
     * Set posicao.
     *
     * @param int $posicao
     *
     * @return FrigaClassificacao
     */
    public function setPosicao($posicao)
    {
        $this->posicao = $posicao;

        return $this;
    }

    /**
     * Get posicao.
     *
     * @return int
     */
    public function getPosicao()
    {
        return $this->posicao;
    }

    /**
     * Set empate.
     *
     * @param bool $empate
     *
     * @return FrigaClassificacao
     */
    public function setEmpate($empate)
    {
        $this->empate = $empate;

        return $this;
    }

    /**
     * Get empate.
     *
     * @return bool
     */
    public function getEmpate()
    {
        return $this->empate;
    }

    /**
     * Set uuid.
     *
     * @param string $uuid
     *
     * @return FrigaClassificacao
     */
    public function setUuid($uuid)
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * Get uuid.
     *
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Set registroDataCriacao.
     *
     * @param \DateTime $registroDataCriacao
     *
     * @return FrigaClassificacao
     */
    public function setRegistroDataCriacao($registroDataCriacao)
    {
        $this->registroDataCriacao = $registroDataCriacao;

        return $this;
    }

    /**
     * Get registroDataCriacao.
     *
     * @return \DateTime
     */
    public function getRegistroDataCriacao()
    {
        return $this->registroDataCriacao;
    }

    /**
     * Set registroDataAtualizacao.
     *
     * @param \DateTime $registroDataAtualizacao
     *
     * @return FrigaClassificacao
     */
    public function setRegistroDataAtualizacao($registroDataAtualizacao)
    {
        $this->registroDataAtualizacao = $registroDataAtualizacao;

        return $this;
    }

    /**
     * Get registroDataAtualizacao.
     *
     * @return \DateTime
     */
    public function getRegistroDataAtualizacao()
    {
        return $this->registroDataAtualizacao;
    }

    /**
     * Set idEdital.
     *
     * @return FrigaClassificacao
     */
    public function setIdEdital(FrigaEdital $idEdital = null)
    {
        $this->idEdital = $idEdital;

        return $this;
    }

    /**
     * Get idEdital.
     *
     * @return FrigaEdital
     */
    public function getIdEdital()
    {
        return $this->idEdital;
    }

    /**
     * Set idCargo.
     *
     * @return FrigaClassificacao
     */
    public function setIdCargo(FrigaEditalCargo $idCargo = null)
    {
        $this->idCargo = $idCargo;

        return $this;
    }

    /**
     * Get idCargo.
     *
     * @return FrigaEditalCargo
     */
    public function getIdCargo()
    {
        return $this->idCargo;
    }

    /**
     * Set idInscricao.
     *
     * @return FrigaClassificacao
     */
    public function setIdInscricao(FrigaInscricao $idInscricao = null)
    {
        $this->idInscricao = $idInscricao;

        return $this;
    }

    /**
     * Get idInscricao.
     *
     * @return FrigaInscricao
     */
    public function getIdInscricao()
    {
        return $this->idInscricao;
    }

    /**
     * @return int
     */
    public function getPosicaoAnterior()
    {
        return $this->posicaoAnterior;
    }

    /**
     * @param int $posicaoAnterior
     *
     * @return FrigaClassificacao
     */
    public function setPosicaoAnterior($posicaoAnterior)
    {
        $this->posicaoAnterior = $posicaoAnterior;

        return $this;
    }

    /**
     * @return FrigaEditalEtapa
     */
    public function getIdEtapa()
    {
        return $this->idEtapa;
    }

    /**
     * @param FrigaEditalEtapa $idEtapa
     *
     * @return FrigaClassificacao
     */
    public function setIdEtapa($idEtapa)
    {
        $this->idEtapa = $idEtapa;

        return $this;
    }

    /**
     * @return FrigaEditalCota
     */
    public function getIdCota()
    {
        return $this->idCota;
    }

    /**
     * @param FrigaEditalCota $idCota
     *
     * @return FrigaClassificacao
     */
    public function setIdCota($idCota)
    {
        $this->idCota = $idCota;

        return $this;
    }

    /**
     * @return string
     */
    public function getObservacao()
    {
        return $this->observacao;
    }

    /**
     * @param string $observacao
     *
     * @return FrigaClassificacao
     */
    public function setObservacao($observacao)
    {
        $this->observacao = $observacao;

        return $this;
    }

    /**
     * @return Usuario
     */
    public function getIdUsuario()
    {
        return $this->idUsuario;
    }

    /**
     * @param Usuario $idUsuario
     *
     * @return FrigaClassificacao
     */
    public function setIdUsuario($idUsuario)
    {
        $this->idUsuario = $idUsuario;

        return $this;
    }

    /**
     * @return int
     */
    public function getIdSituacao()
    {
        return $this->idSituacao;
    }

    /**
     * @param int $idSituacao
     *
     * @return FrigaClassificacao
     */
    public function setIdSituacao($idSituacao)
    {
        $this->idSituacao = $idSituacao;

        return $this;
    }

    /**
     * @return \stdClass
     */
    public function getObjsituacao()
    {
        $obj = new \stdClass();
        $obj->id = $this->idSituacao;
        $obj->descricao = '';

src/Nte/Aplicacao/FrigaBundle/Resources/views/Resultado/index-etapa.html.twig
{% extends 'base.admin.html.twig' %}
{% block titulo %} Resultados {{ edital.uuid }}{% endblock %}
{% block breadcumbsTitulo %} Resultados  {% endblock %}
{% block breadcumbsItens %}
    <li><span><a href="{{ path('nte_aplicacao_friga_etapa_index',{edital: edital.id, tipo:4}) }}"> Resultados</a></span></li>
    <li><span><a href="{{ path('nte_aplicacao_friga_etapa_index',{edital: edital.id}) }}"> {{ edital.uuid }}</a></span></li>
    <li><span><a href="#"> Resultados </a></span></li>
{% endblock %}
{% block conteudo %}
    <div class="row text-right">
        <div class="btn-group">
            {% if geral.empty %}
                {% if is_granted('ROLE_ADMIN') or
                    ( is_granted('ROLE_AVALIADOR') and etapa.periodoHabilitado ) %}
                    <a class="btn btn-success"
                       title="Clique aqui para gerar a grade de resultados"
                       href="{{ path('resultado_etapa_classificacao_gerar', {'etapa': etapa.id}) }}">
                        <i class="fa fa-cog"></i> Gerar Resultados
                    </a>
                {% endif %}
                <a class="btn btn-default"
                   title="Clique aqui para ver a prévia dos resultados"
                   href="{{ path('resultado_parcial', {'etapa': etapa.id}) }}">
                    <i class="icon icon-eye"></i> Prévia
                </a>
            {% else %}
                <a class="btn btn-default"
                   title="Clique aqui para exportar os resultados em arquivo de planilha eletrônica no formato CSV"
                   href="{{ path('resultado_etapa_exportar_csv', {'etapa': etapa.id}) }}">
                    <i class="fa fa-file-excel-o"></i> Exportar
                </a>
                <a class="btn btn-default"
                   title="Clique aqui para imprimir a grade de resultados"
                   href="{{ path('resultado_etapa_impressao', {'etapa': etapa.id}) }}">
                    <i class="icon icon-printer"></i> Imprimir
                </a>
                {% if is_granted('ROLE_AVALIADOR') and etapa.periodoHabilitado %}
                    <a class="btn btn-danger"
                       title="Clique aqui para remover os resultados da etapa"
                       href="{{ path('resultado_etapa_classificacao_remover', {'etapa': etapa.id}) }}">
                        <i class="fa fa-trash"></i> Remover
                    </a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="panel-body text-primary" >
            <h5><strong>{{ etapa.descricao|upper }}</strong></h5>
            {% if etapa.periodoHabilitado %}
            <p>
                <strong>OBSERVAÇÃO: </strong><br>
                Os resultados desta etapa, estarão públicos a partir de
                <b>  {{ etapa.dataDivulgacao|date('d/m/Y \\á\\s H:i:s') }}</b>
            </p>
            {% else %}
                    <small title="Período em que o avaliador poderá gerar os resultados da etapa.">
                        <i class="fa fa-calendar"></i>
                        &nbsp;&nbsp; De: {{ etapa.dataInicial|date('d/m/Y')}} até {{ etapa.dataFinal|date('d/m/Y \\á\\s H:i:s')}}
                    </small>
            {% endif %}

        </div>
    </div>

    <div class="row">
        {% for chave, lista in classificacao %}
            <div class="panel-body">

                <table class="table">
                    <thead>
                    <tr>
                        <th {% if edital.modeloInscricao == 1 %}colspan="3" {% else%} colspan="2"{% endif%} class="text-primary">
                            <i class="icon icon-trophy"></i> &nbsp;
                            {{ lista.nome }}
                        </th>
                        <th></th>
                        <th></th>

                    </tr>
                    <tr>
                        <th width="10">Inscrição</th>
                        {% if edital.modeloInscricao == 1 %}
                            <th>Projeto</th>
                            <th>Participantes</th>
                        {% else %}
                            <th>Nome</th>
                        {% endif %}
                        <th width="10" class="text-center">Situação</th>
                        <th width="70" class="b1 b2 b3 text-center c">
                            Pontuação
                        </th>
                        <th width="200" class="text-center">Classificação</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for cc in lista.classificacao %}
                        <tr class="{% if cc.empate %}b2{% endif %}">
                            <td>{{ cc.idInscricao.uuid }}</td>
                            {% if edital.modeloInscricao == 1 %}
                                <td>
                                    <a title=""
                                       href="{{ path('relatorio_perfil', {'uuid': cc.idInscricao.uuid}) }}">
                                        <b class="text-uppercase">{{ cc.idInscricao.projetoTitulo }}</b>
                                    </a>
                                    {% if cc.observacao %}
                                        <br>
                                        <small>{{ cc.observacao }}</small>
                                    {% endif %}
                                </td>
                                <td>
                                    {% for p in cc.idInscricao.idProjetoParticipante %}
                                        {{ p.nome }}<br>
                                    {% endfor %}
                                </td>
                            {% else %}
                            <td>
                                <a title=""
                                   href="{{ path('relatorio_perfil', {'uuid': cc.idInscricao.uuid}) }}">
                                    <b class="text-uppercase">{{ cc.idInscricao.nome }}</b> </a>
                                {% if cc.observacao %}
                                    <br>
                                    <small>{{ cc.observacao }}</small>
                                {% endif %}
                            </td>
                            {% endif %}
                            <td class="text-right">
                                <div class="{{ cc.objsituacao.css }}">
                                    <i class="{{ cc.objsituacao.icone }}"></i>
                                    {{ cc.objsituacao.descricao }}
                                </div>
                            </td>
                            <td class="b1 b2 b3 text-center">{{ cc.valor+0 }}</td>
                            <td class="text-center">
                                {% if cc.idSituacao == 0
                                    or cc.idSituacao == 1
                                    or cc.idSituacao == 3
                                    or cc.idSituacao == 5 %}
                                    -
                                {% else %}
                                    {% if cc.empate and etapa.periodoHabilitado %}
                                        <form action="{{ path('resultado_etapa_candidato_posicao_confirmar', {'etapa': etapa.id}) }}"
                                              method="post">
                                            <div class="btn-group btn-group-sm">
                                                <input type="hidden" name="c" value="{{ cc.id }}">
                                                <input type="hidden" name="o" value="">
                                                <button type="submit" class="btn btn-default"
                                                        title="Clique aqui para confirmar a posição do candidato e remover a situação de empate">
                                                    Confirmar {{ cc.posicao }}° posição
                                                </button>
                                                <a class="btn btn-success"
                                                   title="Clique aqui para subir a posição do candidato na lista de classificação"
                                                   href="{{ path('resultado_etapa_candidato_posicao', {'etapa': etapa.id, 'uuid': cc.uuid}) }}">
                                                    <i class="fa fa-chevron-up"></i>
                                                </a>
                                            </div>
                                        </form>
                                    {% else %}
                                        {{ cc.posicao }}°
                                    {% endif %}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    {% if lista.classificacao.count<1 %}
                        <tr>
                            <td colspan="5">Nenhum candidato classificado.</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
                <div class="col-md-8 text-left">
                    <b>
                        Cálculo da pontuação:
                        {% for p in edital.pontuacaoCategoriaPeso %}
                            ({{ p.descricao }}) x {{ p.valorMaximo+0 }}  {% if loop.last == 0 %} + {% endif %}
                        {% endfor %}
                        = (Pontuação Total)
                    </b>
                </div>
            </div>
            <br><br>
        {% endfor %}
    </div>
    <style>
        .table > thead > tr > .b {
            border-top: 1px solid #c7d5de !important;
            border-bottom: 0 !important;
        }

        .table > thead > tr > .c {
            border-top: 1px solid #c7d5de !important;
            border-bottom: 0 !important;
        }

        .b {
            border-top: 1px solid #c7d5de;
        }

        .table > tfoot > tr > .d {
            border-bottom: 1px solid #c7d5de;
        }

        .b1 {
            border-left: 1px solid #c7d5de;
        }

        .b3 {
            border-right: 1px solid #c7d5de;
        }

        .b1, .b2, .b3 {
            background-color: #E3F2FD;
            border-bottom: 0px;
        }
    </style>
{% endblock %}
{% block javascripts2 %}
    <link href="{{ asset('assets/vendor/sweetalert2/dist/sweetalert2.min.css') }}" type="text/css"/>
    <script src="{{ asset('assets/vendor/sweetalert2/dist/sweetalert2.all.min.js') }}"></script>
    <script>
        $('form').submit(e => {
            let i1 = e.target[1], form = e.target;
            Swal.fire({
                title: "Confirmar classificação",
                allowOutsideClick: false,
                showCancelButton: true,
                html:
                    '<textarea required="true"  id="obs" class="swal2-input form-control" placeholder="Observações sobre o critério de desempate"></textarea>',
                confirmButtonText: "confirmar!",
                cancelButtonText: "Cancelar",
            }).then((value) => {
                if (value.value) {
                    i1.value = document.getElementById('obs').value;
                    if (i1.value.length) {
                        form.submit();
                    }
                }
            });
            return false;
        })
    </script>
{% endblock %}

src/Nte/Aplicacao/FrigaBundle/Resources/views/Resultado/parcial.html.twig
{% extends 'base.admin.html.twig' %}
{% block titulo %} Resultado Final {% endblock %}
{% block breadcumbsTitulo %} Resultado Parcial  {% endblock %}
{% block breadcumbsItens %}
    <li><span><a href="{{ path('nte_aplicacao_friga_etapa_index',{edital: edital.id, tipo:4}) }}"> Resultados</a></span></li>
    <li><span><a href="{{ path('nte_aplicacao_friga_etapa_index',{edital: edital.id}) }}"> {{ edital.uuid }}</a></span></li>
    <li><span><a href="#"> Prévia </a></span></li>
{% endblock %}
{% block conteudo %}
    <div class="row">
        <div class="panel-body">
            <strong>Prévia dos resultados </strong><br>
            Na prévia de resultados, os critérios de desempate definidos em edital,
            não serão  aplicados no ranqueamento da listagem de  classificação.
        </div>
        <br><br>
        {% for chave, lista in classificao %}
            <div class="panel-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th {% if edital.modeloInscricao == 1 %}colspan="3" {% else%} colspan="2"{% endif%} class="text-primary">
                            <i class="icon icon-trophy"></i> &nbsp;
                            {{ lista.nome }}
                        </th>
                        <th class="text-center b b1 b3" colspan="{{ edital.pontuacaoCategoriaPeso.count + 1 }}">
                            Pontuação
                        </th>
                        <th></th>
                    </tr>
                    <tr>
                        <th width="10">Inscrição</th>
                        {% if edital.modeloInscricao == 1 %}
                            <th>Projeto</th>
                            <th>Participantes</th>
                        {% else %}
                        <th>Nome</th>
                        {% endif %}
                        {% for p in edital.pontuacaoCategoriaPeso %}
                            <th width="70"
                                    class="{% if loop.first %}b1{% else %}b2{% endif %} text-center c">
                                {{ p.descricao }}
                            </th>
                        {% endfor %}
                        <th width="70" class="b3 text-center c">
                            Total
                        </th>
                        <th width="10" class="text-center">Posição</th>
                        <th width="70" class="text-center">Situação</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% set posicao =1 %}
                    {% for inscricao in lista.classificacao %}
                        {% if inscricao.idSituacao != 3 and inscricao.idSituacao != 1 %}
                            <tr>
                                <td width="10">{{ inscricao.uuid }}</td>

                                {% if edital.modeloInscricao == 1 %}
                                    <td>

                                        <a title="{{ inscricao.idCargo.descricao }}{% if inscricao.idCota %}/{{ inscricao.idCota.descricao }}{% endif %}"
                                           href="{{ path('relatorio_perfil', {'uuid': inscricao.uuid}) }}">
                                            <b class="text-uppercase">{{ inscricao.projetoTitulo }}</b> </a>
                                    </td>
                                    <td>
                                        {% for p in inscricao.idProjetoParticipante %}
                                            {{ p.nome }}<br>
                                        {% endfor %}
                                    </td>
                                {% else %}
                                    <td>

                                        <a title="{{ inscricao.idCargo.descricao }}{% if inscricao.idCota %}/{{ inscricao.idCota.descricao }}{% endif %}"
                                           href="{{ path('relatorio_perfil', {'uuid': inscricao.uuid}) }}">
                                            <b class="text-uppercase">{{ inscricao.nome }}</b> </a>
                                    </td>
                                {% endif %}
                                {% for p in edital.pontuacaoCategoriaPeso %}
                                    <td width="70"
                                        class="{% if loop.first %}b1{% else %}b2{% endif %} text-center ">
                                        {{ inscricao.pontuacaoSoma(true,p) }}

                                    </td>
                                {% endfor %}
                                <td width="70" class="b3 text-center">{{ inscricao.pontuacaoSoma(true) }}</td>
                                <td width="10" class="text-center">{{ posicao }}°</td>
                                <td width="10" class="text-right">
                                    <div class="{{ inscricao.objsituacao.css }}">

                                        <i class="{{ inscricao.objsituacao.icone }}"></i>
                                        {{ inscricao.objsituacao.descricao }}
                                    </div>
                                </td>
                            </tr>
                            {% set posicao=posicao+1 %}
                        {% endif %}
                    {% endfor %}
                    {% for inscricao in lista.classificacao %}
                        {% if inscricao.idSituacao == 3 or inscricao.idSituacao == 1 %}
                            <tr>
                                <td width="10">{{ inscricao.uuid }}</td>

                                {% if edital.modeloInscricao == 1 %}
                                    <td>

                                        <a title="{{ inscricao.idCargo.descricao }}{% if inscricao.idCota %}/{{ inscricao.idCota.descricao }}{% endif %}"
                                           href="{{ path('relatorio_perfil', {'uuid': inscricao.uuid}) }}">
                                            <b class="text-uppercase">{{ inscricao.projetoTitulo }}</b> </a>
                                    </td>
                                    <td>
                                        {% for p in inscricao.idProjetoParticipante %}
                                            {{ p.nome }}<br>
                                        {% endfor %}
                                    </td>
                                {% else %}
                                    <td>

                                        <a title="{{ inscricao.idCargo.descricao }}{% if inscricao.idCota %}/{{ inscricao.idCota.descricao }}{% endif %}"
                                           href="{{ path('relatorio_perfil', {'uuid': inscricao.uuid}) }}">
                                            <b class="text-uppercase">{{ inscricao.nome }}</b> </a>
                                    </td>
                                {% endif %}
                                {% for p in edital.pontuacaoCategoriaPeso %}
                                    <td width="70"
                                        class="{% if loop.first %}b1{% else %}b2{% endif %} text-center ">
                                        {{ inscricao.pontuacaoSoma(true,p) }}

                                    </td>
                                {% endfor %}
                                <td width="70" class="b3 text-center">{{ inscricao.pontuacaoSoma(true) }}</td>
                                <td width="10" class="text-center">-</td>
                                <td width="10" class="text-right">
                                    <div class="{{ inscricao.objsituacao.css }}">

                                        <i class="{{ inscricao.objsituacao.icone }}"></i>
                                        {{ inscricao.objsituacao.descricao }}
                                    </div>
                                </td>
                            </tr>
                        {% endif %}

                    {% endfor %}
                    {% if lista.classificacao.count<1 %}
                        <tr>
                            <td colspan="5">Nenhum candidato classificado.</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>

                <div class="col-md-8 text-left">
                    <b>
                        Cálculo da pontuação:
                        {% for p in edital.pontuacaoCategoriaPeso %}
                            ({{ p.descricao }}) x {{ p.valorMaximo+0 }}  {% if loop.last == 0 %} + {% endif %}
                        {% endfor %}
                        = (Pontuação Total)
                    </b>
                </div>
                {#<a href="{{ path('frigaclassificacao_lista_polos_impressao',{id: frigaPolo.id}) }}" class="btn btn-primary pull-right"><i class="fa fa-print"></i> Imprimir</a>#}
            </div>
            <br><br>
        {% endfor %}
    </div>
    <style>
        .table > thead > tr > .b {
            border-top: 1px solid #c7d5de !important;
            border-bottom: 0 !important;
        }

        .table > thead > tr > .c {
            border-top: 1px solid #c7d5de !important;
            border-bottom: 0 !important;
        }

        .b {
            border-top: 1px solid #c7d5de;
        }

        .table > tfoot > tr > .d {
            border-bottom: 1px solid #c7d5de;
        }

        .b1 {
            border-left: 1px solid #c7d5de;
        }

        .b3 {
            border-right: 1px solid #c7d5de;
        }

        .b1, .b2, .b3 {
            background-color: #E3F2FD;
            border-bottom: 0px;
        }
    </style>
{% endblock %}
{% block javascripts2 %}
    <script>
        $('select').select2({
            width: '100%',
        });
    </script>
{% endblock %}